### PR TITLE
Allow non-base locales to ignore arguments

### PR DESCRIPTION
**Pull request by kierangilliam**
Allows for:

```
// en
"key": "Hello {name:string|uppercase}!"

// de
"key": "Hallo!{name|ignore}"

L.key({ name: "George" })
// en: Hello GEORGE!
// de: Hallo!
```

### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time.
- [ ] Prefix your PR title with `[feat]`, `[fix]`, `[chore]`, or `[docs]`.
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`

## generator

If you change something in the `generator`, please also:
 - add some snapshot tests to the `packages/generator/test/generator.test.ts`-file
 - then run `pnpm test` => you should see your tests failing
 - run `pnpm test:update-generated-files`
 - again run `pnpm test` => your tests should pass
 - then add all the created `*.expected.*`-files to the git-index and
 - make sure these files look like you would expect them
 - finally commit these files to the repository

### CODE REVIEW

**Comment by ivanhofer** [comment]
Hi @kierangilliam,
can you please explain your use-case?
It would help me better understand if I want to add and maintain this feature :)

**Comment by kierangilliam** [comment]
Hi @ivanhofer! So sorry - I thought I had included the reasoning.

I'm looking for a framework that will allow ignoring keys. 

I'll have multiple versions of the same language for translations. Some will include the keys in the base translation, others won't. 

The approaches to ignoring keys that you describe in the README did not work for my use-case.

**Comment by ivanhofer** [comment]
Alright, thanks for the explanation. I'm thinking about another implementation.
What about marking the parameter as optional with `?`.
The concept of optional params exists already but it currently only get's applied when calling the translation function

```ts
LL.key({ name: 'John' })
LL.key({ }) // you can omit the name parameter here
```

It would also make sense to be able to ignore the param when writing a translation
```ts
// en
"key": "Hello {name?:string|uppercase}!"
// de
"key": "Hallo!" // this is currenlty not supported
```

What do you think?

**Comment by ivanhofer** [comment]
Closing in favour of #422

**Comment by ivanhofer** [comment]
@kierangilliam you should be able to do the following in version `5.12.0` I just released:

```ts
// en
"key": "Hello {name?:string|uppercase}!"

// de
"key": "Hallo!"

L.key({ name: "George" })
// en: Hello GEORGE!
// de: Hallo!
```

**Pull request closed without merging**
